Feature branch
ANTOINE1128/Awesome-Books pull request #1
Opened 2023-05-02 18:32 UTC by ANTOINE1128

2023-05-02 18:44 UTC, addod19 commented
### Hi @ANTOINE1128 and @10-menachi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the PR has no description and the README file is not professional. Kindly take a second look at the project description or better still check this [link](https://github.com/microverseinc/readme-template) to help make the README file better 
![Screenshot from 2023-05-02 18-49-49](https://user-images.githubusercontent.com/46388113/235756972-2112aba1-effa-4fee-ab00-7ff0dc845036.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-02 19:13 UTC, Shisui6 requested changes
Hi @ANTOINE1128 and @10-menachi, 

# Requires Changes 🍀
You have done a great job so far!👏
Your design is good 🖼️, and your code follows best practices. However, there are a few issues that you still need to work on🪲.

## Highlights
- Nice use of javascript classes ✅
- App works as expected ✅


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 19:13 UTC, Shisui6 commented on app.js
Please remove all files that are not being used from your project. This will help to keep your codebase clean👍

2023-05-02 19:13 UTC, Shisui6 commented on app2.js
Please remove all files that are not being used from your project. This will help to keep your codebase clean👍

2023-05-02 19:13 UTC, Shisui6 commented on index.html
> +<!-- <script src="app.js"></script> -->
Please remove all commented-out code from your project. This will help keep your codebase clean and easy to refactor👍

2023-05-02 19:13 UTC, Shisui6 commented on app1.js
> +// const booksSection = document.querySelector('.books');
Please remove all commented-out code from your project. This will help keep your codebase clean and easy to refactor👍

2023-05-02 21:19 UTC, GzimAsani requested changes
### Hello, TEAM             :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with removing the unused file :+1: 

 ## Required Changes 

- [ ] Check the comments below :arrow_double_down:  

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers, and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 21:19 UTC, GzimAsani commented on index.html
> +<!-- <script src="app.js"></script> -->
- [ ] As suggested by the previous reviewer, please remove all the commented-out code. This will make your codebase looks better and cleaner

2023-05-02 21:19 UTC, GzimAsani commented on app1.js
> +// const booksSection = document.querySelector('.books');
- [ ] As suggested by the previous reviewer, please remove all the commented-out code. This will make your codebase looks better and cleaner

2023-05-03 05:13 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @ANTOINE1128 and @10-menachi 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 11:59 UTC, merged